# URL:     https://raw.githubusercontent.com/chrisqin/UnblockNeteaseMusic/master/config.yaml


proxies:
  - name: ğŸ¶ ç½‘æ˜“äº‘è§£é”-ç”µä¿¡
    type: http
    server: sjy.losfa.xyz
    port: 9527

  - name: ğŸ¶ ç½‘æ˜“äº‘è§£é”-ç§»åŠ¨1Gbps
    type: http
    server: www.losfa.xyz
    port: 34567
